#!/bin/bash

xdotool search --name "Minecraft 1.9" windowactivate --sync 	key e

i=0

while (true)
do
    i=$((i+1))
    #xdotool search --name "Minecraft 1.9" windowactivate --sync key 1 sleep 0.1 click 1 sleep 1
    for k in 1 2 3 4 5 6 7 8 9
    do
        xdotool search --name "Minecraft 1.9" windowactivate --sync click 1 sleep 0.2 key $k sleep 1
    done
    echo -n "$i "
done
echo
