#!/bin/bash

xdotool search --name "Minecraft 1.9" windowactivate --sync 	key e

i=0

while (true)
do
    i=$((i+1))
    xdotool search --name "Minecraft 1.9" windowactivate --sync sleep 1 key 1 sleep 1.5 click 1 sleep 1
    for sec in {1..3}
    do
      for k in 1 2 3 4 5
      do
          xdotool search --name "Minecraft 1.9" windowactivate --sync key $k sleep 2
      done
    done
    echo -n "$i "
done
echo
