#!/bin/bash

sleeptime="0.7"

xdotool search --name "Minecraft 1.9.3-pre2" windowactivate --sync 	key e sleep 0.5 key 1 sleep $sleeptime

i=0

while (true)
do
    i=$((i+1))
    for k in 1 2 3 4 5 6 7 8 9
    do
	xdotool search --name "Minecraft 1.9.3-pre2" windowactivate --sync click 1 sleep $sleeptime key $k sleep $sleeptime
    done
    echo -n "$i "
done
echo
