#!/bin/bash

xdotool search --onlyvisible --name "Minecraft 16w15b" windowactivate --sync 	key e

i=0

while (true)
do
    i=$((i+1))
    xdotool search --onlyvisible --name "Minecraft 16w15b" windowactivate --sync click 1 sleep 0.6
    echo -n "$i "
done
echo
