#!/usr/bin/perl -w

use strict;
use utf8;
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use JSON;
use Time::HiRes qw (sleep);
use POSIX qw(strftime);
use Data::Dumper;
use lib './lib';
use Minecraft::L10n;
use Minecraft::Window;
$main::config = Minecraft::FileIO::read_config();
# $main::l10n   = Minecraft::L10n->new();

sub capture_screen
{

  Minecraft::Window::restore_size_and_position();
  system(sprintf('ffmpeg -video_size %dx%d -framerate 25 -f x11grab -i :0.0+%d,%d -f alsa -ac 2 -i hw:0 %s/%s_capture.mkv',
                $main::config->{'system'}{'window'}{'geometry'}{'w'},
                $main::config->{'system'}{'window'}{'geometry'}{'h'},
                $main::config->{'system'}{'window'}{'geometry'}{'x'},
                $main::config->{'system'}{'window'}{'geometry'}{'y'},
                $main::config->{'user'}{'paths'}{'screenshosts'},
                strftime("%d.%m.%Y_%H-%M-%S", localtime)));
}

capture_screen();