#!/usr/bin/perl -w

use strict;
use JSON;
use Time::HiRes qw (sleep);
use Data::Dumper;
use lib './lib';
use Minecraft::Automation;
use Minecraft::Screenshoter;

my $config = Minecraft::Automation::read_config();

sub get_cursor_position
{
    my $text = $_[0];
    Minecraft::Automation::say($text);
    my @tmp = split(/ /, `./get-mouse-position`);
    #print Dumper(@tmp);
    return {
                'x' => ($tmp[0]+0) > $config->{'system'}{'window'}{'geometry'}{'x'} ? ($tmp[0]+0) - $config->{'system'}{'window'}{'geometry'}{'x'} : $config->{'system'}{'window'}{'geometry'}{'x'} - ($tmp[0]+0),
                'y' => ($tmp[1]+0) > $config->{'system'}{'window'}{'geometry'}{'y'} ? ($tmp[1]+0) - $config->{'system'}{'window'}{'geometry'}{'y'} : $config->{'system'}{'window'}{'geometry'}{'y'} - ($tmp[1]+0)
            };
}

sub get_cell_coordinates
{
    my $text = $_[0];
    my $tmp = {};
    $tmp->{'tl'} = get_cursor_position("$text. Кликните в левом верхнем углу ячейки");
    $tmp->{'br'} = get_cursor_position("$text. Кликните в правом нижнем углу ячейки");
    $tmp->{'c'} = 
            {
                'x' => int($tmp->{'tl'}{'x'} + ($tmp->{'br'}{'x'} - $tmp->{'tl'}{'x'})/2),
                'y' => int($tmp->{'tl'}{'y'} + ($tmp->{'br'}{'y'} - $tmp->{'tl'}{'y'})/2)
            };
    #print Dumper($tmp);
    return $tmp;
}

sub get_button_coordinates
{
    my $text = $_[0];
    my $tmp = {};
    $tmp->{'c'} = get_cursor_position("$text. Нажмите эту кнопку, старайтесь жать посередине кнопки");
    return $tmp;
}

sub get_windowsizeposition
{
    Minecraft::Automation::wait_any_key("Расположите окно майнкрафта так, как вам привычно и удобно");
    $config = Minecraft::Screenshoter::get_window_size_position();
}

sub get_crafttable_cells
{
    Minecraft::Automation::wait_any_key("Откройте интерфейс стола крафтинга");
    $config->{'system'}{'no-interface'} = get_button_coordinates("Кликните вне интерфейса, но в окне майна. Желательно посередине окна, как можно ниже. Эта точка будет использоваться для скрытия мыша и для дропа");
    Minecraft::Automation::say("Нумерация ячеек следующая:\n0:0 1:0 2:0\n0:1 1:1 2:1\n0:2 1:2 2:2");
    for my $y (0..2)
    {
        for my $x (0..2)
        {
            $config->{'system'}{'crafttable'}{$x}{$y} = get_cell_coordinates("Ячейка $x:$y стола крафта");
        }
    }
    $config->{'system'}{'crafttable'}{'result'} = get_cell_coordinates("Ячейка результата стола крафта");
    $config->{'system'}{'crafttable'}{'clean'} = get_cell_coordinates("Пустое место в интерфейсе размером с ячейку, советую где нибудь под стрелкой, указывающей на результат");
    Minecraft::Screenshoter::take_screenshot("dont-delete-crafttable-clean", $config->{'system'}{'crafttable'}{'clean'});
}

sub get_invertory_cells
{
    Minecraft::Automation::wait_any_key("Опять откройте интерфейс стола крафтинга, теперь будем выяснять где у нас инвертарь");
    Minecraft::Automation::say("Нумерация ячеек следующая:\n0:0 1:0 2:0 3:0 4:0 5:0 6:0 7:0 8:0\n0:1 1:1 2:0 3:1 4:0 5:1 6:1 7:1 8:1\n0:2 1:2 2:0 3:2 4:0 5:2 6:2 7:2 8:2\n0:3 1:3 2:0 3:3 4:0 5:3 6:3 7:3 8:3");
    for my $y (0..3)
    {
        for my $x (0..8)
        {
            $config->{'system'}{'invertory'}{$x}{$y} = get_cell_coordinates("Ячейка $x:$y инвертаря");
        }
    }
}

sub get_villager_interface
{
    Minecraft::Automation::wait_any_key("Откройте интерфейс торговли");
    $config->{'system'}{'villager'}{'invertory'}{0} = get_cell_coordinates("Левая ячейка инвертаря крестьянина");
    $config->{'system'}{'villager'}{'invertory'}{1} = get_cell_coordinates("Правая ячейка инвертаря крестьянина");
    $config->{'system'}{'villager'}{'result'} = get_cell_coordinates("Ячейка результата торговли крестьянина (справа которая)");
    $config->{'system'}{'villager'}{'clean'} = get_cell_coordinates("Пустое место в интерфейсе размером с ячейку, советую справа, под кнопкой перелистывания страницы вперед");
    Minecraft::Automation::wait_any_key("Теперь переключитесь на страницу торговли, где крестьянин еще может торговать (стрелки не перечеркнуты)");
    $config->{'system'}{'villager'}{'trade-avialable'} = get_cell_coordinates("Верхняя стрелка");
	Minecraft::Automation::wait_any_key("Теперь надо найти крестьянина минимум с тремя доступными страницами торговли (потребуется дважды жать на кнопки)");
	$config->{'system'}{'villager'}{'next_page'} = get_cell_coordinates("Кнопка переключения на следующую страницу торговли");
	$config->{'system'}{'villager'}{'prev_page'} = get_cell_coordinates("Кнопка переключения на предыдущую страницу торговли");
	for my $button_name ('next_page', 'prev_page')
	{
		Minecraft::Automation::mouse_move_to_button($config->{'system'}{'villager'}{$button_name});
		for (0..15)
		{
			Minecraft::Automation::mouse_left_click();
		}
		Minecraft::Automation::mouse_move_to_cell({ 'c' => {'x' => 10, 'y' => 10 } });
		sleep(0.5);
		Minecraft::Screenshoter::take_screenshot(sprintf("dont-delete-villager-%s-not-avialable", $button_name), $config->{'system'}{'villager'}{$button_name});
	}

    Minecraft::Screenshoter::take_screenshot("dont-delete-villager-trade-avialable", $config->{'system'}{'villager'}{'trade-avialable'});
    Minecraft::Screenshoter::take_screenshot("dont-delete-villager-invertory-0", $config->{'system'}{'villager'}{'invertory'}{0});
    Minecraft::Screenshoter::take_screenshot("dont-delete-villager-invertory-1", $config->{'system'}{'villager'}{'invertory'}{1});
    Minecraft::Screenshoter::take_screenshot("dont-delete-villager-result-empty", $config->{'system'}{'villager'}{'result'});
    Minecraft::Screenshoter::take_screenshot("dont-delete-villager-clean", $config->{'system'}{'villager'}{'clean'});
}

sub test_crafttable
{
    Minecraft::Automation::wait_any_key("Показываю ячейки стола крафта. Если вы правильно их отмечали, курсор будет приблизительно посередине каждой ячейки");
    for my $y (0..2)
    {
        for my $x (0..2)
        {
            Minecraft::Automation::mouse_move_to_cell($config->{'system'}{'crafttable'}{$x}{$y});
            sleep(0.5);
        }
    }
    Minecraft::Automation::mouse_move_to_cell($config->{'system'}{'crafttable'}{'result'});
    sleep(0.5);
}

sub test_invertory
{
    Minecraft::Automation::wait_any_key("Показываю ячейки инвертаря. Если вы правильно их отмечали, курсор будет приблизительно посередине каждой ячейки");
    for my $y (0..3)
    {
        for my $x (0..8)
        {
            Minecraft::Automation::mouse_move_to_cell($config->{'system'}{'invertory'}{$x}{$y});
            sleep(0.5);
        }
    }
}

sub test_villager_interface
{
    Minecraft::Automation::wait_any_key("Показываю интерфейс торговли. Если вы правильно их отмечали, курсор будет приблизительно посередине каждой ячейки и верхней стрелки");
    Minecraft::Automation::mouse_move_to_cell($config->{'system'}{'villager'}{'next_page'}); sleep(0.5);
    Minecraft::Automation::mouse_move_to_cell($config->{'system'}{'villager'}{'prev_page'}); sleep(0.5);
    Minecraft::Automation::mouse_move_to_cell($config->{'system'}{'villager'}{'invertory'}{0}); sleep(0.5);
    Minecraft::Automation::mouse_move_to_cell($config->{'system'}{'villager'}{'invertory'}{1}); sleep(0.5);
    Minecraft::Automation::mouse_move_to_cell($config->{'system'}{'villager'}{'result'}); sleep(0.5);
    Minecraft::Automation::mouse_move_to_cell($config->{'system'}{'villager'}{'trade-avialable'}); sleep(0.5);
}

sub train_view_item_invertory_and_crafttable
{
    my ($item, $text) = @_[0..1];
    Minecraft::Automation::wait_any_key("Поместите $text ($item) в ячейку 0:0 инвертаря, откройте интерфейс крафта");
    train_view_item_xy($item, 'invertory', 8, 3);
    Minecraft::Automation::put_stack_to_cell($config->{'system'}{'crafttable'}{0}{0});
    train_view_item_xy($item, 'crafttable', 2, 2);
}

sub train_view_empty_invertory_and_crafttable
{
    Minecraft::Automation::wait_any_key("Очистите инвертарь, откройте интерфейс крафта");
    train_view_item_xy('empty', 'invertory', 8, 3);
    train_view_item_xy('empty', 'crafttable', 2, 2);
}

sub train_view_item_xy
{
    my ($item, $where, $max_x, $max_y) = @_[0..3];
    mkdir(sprintf("%s/items/%s/", $config->{'user'}{'paths'}{'screenshosts'}, $item));
    for my $y (0..$max_y)
    {
        for my $x (0..$max_x)
        {
            if($x>0 || $y>0)
            {
                Minecraft::Automation::put_stack_to_cell($config->{'system'}{$where}{$x}{$y});
            }
            Minecraft::Automation::mouse_hide_from_interface();
            Minecraft::Screenshoter::take_item_screenshot($item, $where, $x, $y, $config->{'system'}{$where}{$x}{$y});
            Minecraft::Automation::take_stack_from_cell($config->{'system'}{$where}{$x}{$y});
        }
    }
}

sub train_view_items
{
	mkdir(sprintf("%s/items/", $config->{'user'}{'paths'}{'screenshosts'}));
	train_view_item_invertory_and_crafttable('pumpkin', 'тыкву');
	train_view_item_invertory_and_crafttable('carrot', 'морковь');
	train_view_item_invertory_and_crafttable('potato', 'картофель');
	train_view_item_invertory_and_crafttable('wheat', 'пшеницу');
	train_view_item_invertory_and_crafttable('block-melon', 'блок арбуза');
	train_view_item_invertory_and_crafttable('raw-chicken', 'сырую курятину');
	train_view_item_invertory_and_crafttable('raw-porkchop', 'сырую свинину');
	train_view_item_invertory_and_crafttable('rotten-flesh', 'гнилую плоть');
	train_view_item_invertory_and_crafttable('coal', 'уголь');
	train_view_item_invertory_and_crafttable('paper', 'бумагу');
	train_view_item_invertory_and_crafttable('string', 'нить');
	train_view_item_invertory_and_crafttable('emerald', 'изумруд');
	train_view_empty_invertory_and_crafttable();
}

Minecraft::Automation::say("Начинаем настройку. Следуйте рекомендациям тут.");
get_windowsizeposition();
Minecraft::Automation::say("Дальше надо будет кликать по углам ячеек. Правильное наведение на угол - это когда ячейка остается 'подсвеченой'. Старайтесь попадать в углы максимально точно. Удобнее будет, если инвертарь будет пуст");
get_crafttable_cells();
get_invertory_cells();
train_view_items();
test_crafttable();
test_invertory();

Minecraft::Automation::wait_any_key("Теперь вам надо найти крестьянина. Станьте возле него. Проверьте, что у него доступно несколько товаров");
get_villager_interface();
test_villager_interface();



$config = Minecraft::Automation::save_system_config($config);            
#print Dumper($config);
